[package]
name = "aur-search-bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11.6", features = ["json"] }
teloxide = { version = "0.5", features = ["full"] } 
serde = { version = "1.0", features = ["derive"] }
pretty_env_logger = "0.4.0"
tokio-stream = "0.1.8"
serde_json = "1.0"
chrono = "0.4"

log = "0.4"